server:
  port: 8761

eureka:
  instance:                   #定义Eureka实例
    hostname: localhost #Eureka实例所在的主机名

  #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
  client:
    register-with-eureka: false #表示是否将自己注册到Eureka Server上，默认为true
    fetch-registry: false       #表示是否从Eureka Server上获取注册信息，默认为true
  server:
    enable-self-preservation: false #开启Eureka自我保护机制
    eviction-interval-timer-in-ms: 5000 #清理间隔（单位毫秒，默认是60*1000）
    renewal-percent-threshold: 4.5 #自我保护阈值